name: CI/CD Pipeline for HolaMundoMultilenguaje

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      
      - name: Install dev dependencies
        run: composer install --dev 
      
      - name: Run tests
        run: ./vendor/bin/phpunit tests || phpunit tests


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
           
          # Asegurar que la ruta de despliegue existe
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"

          # Sincronizar archivos con el servidor
          rsync -avz --delete-after --exclude 'tests' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH

          # Instalar dependencias en el servidor
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && composer install --no-dev --optimize-autoloader"

          # Reiniciar Apache solo si está instalado
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "if systemctl list-units --type=service | grep -q apache2; then sudo systemctl restart apache2; fi"

          # Limpiar clave SSH después de la ejecución
          ssh-agent -k
          rm -f ~/.ssh/id_rsa
